### ISSUE TITLE
[Regression] Maven Plugin 4.9.5.0 throws `NoClassDefFoundError`

### ISSUE THREAD

**Issue by uhafner** [spotbugs/spotbugs-maven-plugin#1209]
When upgrading `<spotbugs-maven-plugin.version>` from 4.9.4.0 to 4.9.5.0 I get the following exception in my builds:

```
[INFO] --- spotbugs:4.9.5.0:spotbugs (spotbugs) @ coverage-model ---
[INFO] Fork Value is true
     [java] Exception in thread "main" java.lang.NoClassDefFoundError: [Ljavax/annotation/meta/When;
     [java]     at edu.umd.cs.findbugs.ba.jsr305.TypeQualifierAnnotation.<clinit>(TypeQualifierAnnotation.java:97)
     [java]     at edu.umd.cs.findbugs.FindBugs2.clearCaches(FindBugs2.java:344)
     [java]     at edu.umd.cs.findbugs.FindBugs2.execute(FindBugs2.java:327)
     [java]     at edu.umd.cs.findbugs.FindBugs.runMain(FindBugs.java:390)
     [java]     at edu.umd.cs.findbugs.FindBugs2.main(FindBugs2.java:1223)
     [java] Caused by: java.lang.ClassNotFoundException: javax.annotation.meta.When
     [java]     at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
     [java]     at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
     [java]     at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
     [java]     ... 5 more
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  13.308 s
[INFO] Finished at: 2025-09-16T20:55:46+02:00
[INFO] ------------------------------------------------------------------------
```

When downgrading again everything works as expected:

```
[INFO] --- spotbugs:4.9.4.0:spotbugs (spotbugs) @ coverage-model ---
[INFO] Fork Value is true
[INFO] Done SpotBugs Analysis....
[WARNING] Unable to find a URL to the parent project. The parent menu will NOT be added.
[INFO] Rendering content with org.apache.maven.skins:maven-fluido-skin:jar:2.0.0-M9 skin
[INFO] 
```

For reference see https://github.com/jenkinsci/coverage-model/actions/runs/17766920537/job/50492521347?pr=209 and https://github.com/jenkinsci/coverage-model/pull/209. (The parent pom contains the upgrade of `<spotbugs-maven-plugin.version>` from 4.9.4.0 to 4.9.5.0)

**Comment by hazendaz** [comment]
Based on your parent pom, you have an exclusion on jsr305.  The error is due to that.

**Comment by hazendaz** [comment]
The plugin wraps spotbugs, the library is required by spotbugs.  The error is valid in java as user excluded the class.  Are there plans to remove that due to oracle violation, yes but not sure when that actually will occur.  Closing this issue as non issue.  Thanks.
